<a href="https://colab.research.google.com/github/Kamrankhan69/Data-Preprocessing-and-classification/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
path = '/content/drive/My Drive/datasets/covtype.data'

In [ ]:
import pandas as pd
data = pd.read_csv(path, header=0)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581011 entries, 0 to 581010
Data columns (total 55 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   2596    581011 non-null  int64
 1   51      581011 non-null  int64
 2   3       581011 non-null  int64
 3   258     581011 non-null  int64
 4   0       581011 non-null  int64
 5   510     581011 non-null  int64
 6   221     581011 non-null  int64
 7   232     581011 non-null  int64
 8   148     581011 non-null  int64
 9   6279    581011 non-null  int64
 10  1       581011 non-null  int64
 11  0.1     581011 non-null  int64
 12  0.2     581011 non-null  int64
 13  0.3     581011 non-null  int64
 14  0.4     581011 non-null  int64
 15  0.5     581011 non-null  int64
 16  0.6     581011 non-null  int64
 17  0.7     581011 non-null  int64
 18  0.8     581011 non-null  int64
 19  0.9     581011 non-null  int64
 20  0.10    581011 non-null  int64
 21  0.11    581011 non-null  int64
 22  0.12    581011 non-n

In [ ]:
data.isnull().sum()

2596    0
51      0
3       0
258     0
0       0
510     0
221     0
232     0
148     0
6279    0
1       0
0.1     0
0.2     0
0.3     0
0.4     0
0.5     0
0.6     0
0.7     0
0.8     0
0.9     0
0.10    0
0.11    0
0.12    0
0.13    0
0.14    0
0.15    0
0.16    0
0.17    0
0.18    0
0.19    0
0.20    0
0.21    0
0.22    0
0.23    0
0.24    0
0.25    0
0.26    0
0.27    0
0.28    0
0.29    0
0.30    0
0.31    0
1.1     0
0.32    0
0.33    0
0.34    0
0.35    0
0.36    0
0.37    0
0.38    0
0.39    0
0.40    0
0.41    0
0.42    0
5       0
dtype: int64

In [ ]:
# impute missing values via the column mean

from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(data.values)
imputed_data = imr.transform(data.values)
imputed_data

array([[2.590e+03, 5.600e+01, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        5.000e+00],
       [2.804e+03, 1.390e+02, 9.000e+00, ..., 0.000e+00, 0.000e+00,
        2.000e+00],
       [2.785e+03, 1.550e+02, 1.800e+01, ..., 0.000e+00, 0.000e+00,
        2.000e+00],
       ...,
       [2.386e+03, 1.590e+02, 1.700e+01, ..., 0.000e+00, 0.000e+00,
        3.000e+00],
       [2.384e+03, 1.700e+02, 1.500e+01, ..., 0.000e+00, 0.000e+00,
        3.000e+00],
       [2.383e+03, 1.650e+02, 1.300e+01, ..., 0.000e+00, 0.000e+00,
        3.000e+00]])

In [ ]:
len(data)

581011

In [ ]:
len(data)

581011

In [ ]:
data.values

array([[2590,   56,    2, ...,    0,    0,    5],
       [2804,  139,    9, ...,    0,    0,    2],
       [2785,  155,   18, ...,    0,    0,    2],
       ...,
       [2386,  159,   17, ...,    0,    0,    3],
       [2384,  170,   15, ...,    0,    0,    3],
       [2383,  165,   13, ...,    0,    0,    3]])

In [ ]:
import numpy as np

X = data.drop("5",axis=1)
y = data["5"]

print('Class labels:', np.unique(y))

Class labels: [1 2 3 4 5 6 7]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

**Features standardization**

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

# **Perceptron**

In [ ]:
from sklearn.linear_model import Perceptron

ppn = Perceptron(eta0=0.01, random_state=1)
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.01, random_state=1)

In [ ]:
y_pred = ppn.predict(X_test_std)
print('Misclassified examples: %d' % (y_test != y_pred).sum())

Misclassified examples: 64059


**score method does it directly**

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.3f' % ppn.score(X_test_std, y_test))

Accuracy: 0.632


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[38790 21401    14     0    80     3  3264]
 [22039 60785  1345     3   435   230   154]
 [   12  3540  5632   255   125  1162     0]
 [    0    39   344   315     0   126     0]
 [   27  2531    80     0   209     1     0]
 [   37  2626  1418   119   200   810     0]
 [ 2336    87    26     0     0     0  3704]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.61      0.61      0.61     63552
           2       0.67      0.72      0.69     84991
           3       0.64      0.53      0.58     10726
           4       0.46      0.38      0.42       824
           5       0.20      0.07      0.11      2848
           6       0.35      0.16      0.21      5210
           7       0.52      0.60      0.56      6153

    accuracy                           0.63    174304
   macro avg       0.49      0.44      0.45    174304
weighted avg       0.62      0.63      0.63    174304



# **AdaLine**

In [ ]:
class AdalineGD(object):
    """ADAptive LInear NEuron classifier.

    Parameters
    ------------
    eta : float
        Learning rate (between 0.0 and 1.0)
    n_iter : int
        Passes over the training dataset.
    random_state : int
        The seed of the pseudo random number generator.

    Attributes
    -----------
    w_ : 1d-array
        Weights after fitting.
    errors_ : list
        Number of misclassifications in every epoch.

    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state

    def fit(self, X, y):
        """ Fit training data.

        Parameters
        ----------
        X : array-like; shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like; shape = [n_samples]
            Target values or labels.

        Returns
        -------
        self : object

        """
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1+X.shape[1])
        self.cost_ = []

        for i in range(self.n_iter):
            output = self.activation(X)

            # Cost function
            error = (y - output)
            cost = (error**2).sum() / 2.0
            self.cost_.append(cost)

            # Update rule
            self.w_[1:] += self.eta * X.T.dot(error)
            self.w_[0] += self.eta * error.sum()

        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def activation(self, X):
        """Compute linear activation"""
        return self.net_input(X)

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.activation(X) >= 0.0, 1, -1)

In [ ]:
ada = AdalineGD(n_iter=50, eta=0.001).fit(X_train_std, y_train)


y_pred = ada.predict(X_test_std)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))


Misclassified samples: 138348
Accuracy: 0.21


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[    0     0     0     0     0     0     0     0]
 [27596 35956     0     0     0     0     0     0]
 [39532 45459     0     0     0     0     0     0]
 [10726     0     0     0     0     0     0     0]
 [  824     0     0     0     0     0     0     0]
 [ 1792  1056     0     0     0     0     0     0]
 [ 5210     0     0     0     0     0     0     0]
 [ 2616  3537     0     0     0     0     0     0]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           1       0.42      0.57      0.48     63552
           2       0.00      0.00      0.00     84991
           3       0.00      0.00      0.00     10726
           4       0.00      0.00      0.00       824
           5       0.00      0.00      0.00      2848
           6       0.00      0.00      0.00      5210
           7       0.00      0.00      0.00      6153

    accuracy                           0.21    174304
   macro avg       0.05      0.07      0.06    174304
weighted avg       0.15      0.21      0.18    174304



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1


#**SVM**

In [ ]:
from sklearn import svm
from sklearn.metrics import accuracy_score

svmc = svm.SVC().fit(X_train_std, y_train)
y_pred = svmc.predict(X_test_std)

print('Misclassified examples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.3f' % svmc.score(X_test_std, y_test))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


#**Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rfc = RandomForestClassifier(n_estimators = 100)
rfc = rfc.fit(X_train_std, y_train)
y_pred = rfc.predict(X_test_std)

print('Misclassified examples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.3f' % rfc.score(X_test_std, y_test))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))



#**Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dtc = DecisionTreeClassifier(random_state = 0).fit(X_train_std, y_train)
y_pred = dtc.predict(X_test_std)

print('Misclassified examples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.3f' % dtc.score(X_test_std, y_test))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

#**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=5).fit(X_train_std, y_train)
y_pred = knn.predict(X_test_std)

print('Misclassified examples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.3f' % knn.score(X_test_std, y_test))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))